
chunk_file: /data/wzh_fd/workspace/tiny-mm-rag-agent/data/tmp_dfcf/chunks.json

embedding_model: /data/wzh_fd/workspace/Models/gme-Qwen2-VL-2B-Instruct
reranker_model: /data/wzh_fd/workspace/Models/jina-reranker-m0

llm_model: /data/wzh_fd/workspace/Models/Qwen2.5-VL-7B-Instruct